[package]
name = "folder-differ"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
rayon = "1.10"
indicatif = "0.17"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
memmap2 = "0.9"
blake3 = "1.5"
ignore = "0.4"
rustc-hash = "1.1"
num_cpus = "1.16"
